# Generated by Django 3.0.2 on 2020-01-21 06:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', help_text='菜单图标', max_length=50, null=True, verbose_name='菜单图标')),
                ('is_outside', models.BooleanField(help_text='是否为外链接:true/false', verbose_name='是否为外部链接')),
                ('is_show', models.BooleanField(help_text='非管理员是否可见:true/false', verbose_name='非管理员是否可见')),
                ('name', models.CharField(help_text='菜单名称', max_length=50, verbose_name='菜单名称')),
                ('url', models.CharField(help_text='路由地址', max_length=255, verbose_name='路由地址')),
                ('sort', models.IntegerField(blank=True, default=999, help_text='菜单顺序', null=True, verbose_name='菜单顺序')),
                ('superior', models.IntegerField(blank=True, default=0, help_text='上级菜单ID', null=True, verbose_name='上级菜单ID')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '目录配置表',
                'db_table': 'tb_directory',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='用户名', max_length=10, verbose_name='用户名')),
                ('nickname', models.CharField(blank=True, default='', help_text='昵称', max_length=50, null=True, verbose_name='昵称')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')], help_text='性别:1男、2女，3其他', verbose_name='性别')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='电话', max_length=128, null=True, region=None, verbose_name='电话')),
                ('email', models.EmailField(help_text='邮箱', max_length=254, verbose_name='邮箱')),
                ('status', models.IntegerField(help_text='在用状态:1在用、2停用', verbose_name='在用状态')),
                ('level', models.IntegerField(help_text='用户级别:1管理员、2普通用户', verbose_name='用户级别')),
                ('last_time', models.DateTimeField(help_text='上次登录时间', verbose_name='上次登录时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户注册表',
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='角色名称', max_length=50, verbose_name='角色名称')),
                ('data_authority', models.CharField(choices=[(1, '所有数据'), (2, '当前用户数据')], help_text='数据权限', max_length=1, verbose_name='数据权限')),
                ('role_authority', models.CharField(help_text='角色权限', max_length=10, verbose_name='角色权限')),
                ('sort', models.IntegerField(blank=True, default=999, help_text='角色顺序', null=True, verbose_name='角色顺序')),
                ('description', models.TextField(blank=True, default='', help_text='角色描述', null=True, verbose_name='角色描述')),
                ('superior_role', models.CharField(help_text='所配置菜单ID集合', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='所配置菜单ID集合')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('superior', models.ForeignKey(help_text='所属用户ID', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.User', verbose_name='所属用户ID')),
            ],
            options={
                'verbose_name': '角色配置表',
                'db_table': 'tb_user_role',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', help_text='菜单图标', max_length=50, null=True, verbose_name='菜单图标')),
                ('is_outside', models.BooleanField(help_text='是否为外链接:true/false', verbose_name='是否为外部链接')),
                ('is_show', models.BooleanField(help_text='非管理员是否可见:true/false', verbose_name='非管理员是否可见')),
                ('is_cache', models.BooleanField(help_text='是否菜单缓存:true/false', verbose_name='是否菜单缓存')),
                ('name', models.CharField(help_text='菜单名称', max_length=50, verbose_name='菜单名称')),
                ('authority', models.CharField(help_text='权限标识', max_length=10, verbose_name='权限标识')),
                ('url', models.CharField(help_text='路由地址', max_length=255, verbose_name='路由地址')),
                ('sort', models.IntegerField(blank=True, default=999, help_text='菜单顺序', null=True, verbose_name='菜单顺序')),
                ('component_name', models.CharField(help_text='组件名称', max_length=50, verbose_name='组件名称')),
                ('component_url', models.CharField(help_text='组件路径', max_length=255, verbose_name='组件路径')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('superior', models.ForeignKey(help_text='所属目录ID', on_delete=django.db.models.deletion.CASCADE, related_name='dierctory', to='users.Directory', verbose_name='所属目录ID')),
            ],
            options={
                'verbose_name': '菜单配置表',
                'db_table': 'tb_menu',
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='按钮名称', max_length=50, verbose_name='按钮名称')),
                ('authority', models.CharField(help_text='权限标识', max_length=10, verbose_name='权限标识')),
                ('sort', models.IntegerField(blank=True, default=999, help_text='按钮顺序', null=True, verbose_name='按钮顺序')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('superior', models.ForeignKey(help_text='所属菜单ID', on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='users.Menu', verbose_name='所属菜单ID')),
            ],
            options={
                'verbose_name': '按钮配置表',
                'db_table': 'tb_button',
            },
        ),
    ]
