# Generated by Django 3.0.2 on 2020-01-21 06:31

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='superior',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='superior',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='superior',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='superior_role',
        ),
        migrations.AddField(
            model_name='menu',
            name='superior_button',
            field=models.CharField(blank=True, default='', help_text='所关联按钮', max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='所关联按钮'),
        ),
        migrations.AddField(
            model_name='menu',
            name='superior_directory',
            field=models.CharField(blank=True, default='', help_text='所关联目录ID', max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='所关联目录ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='superior_role',
            field=models.CharField(blank=True, default='', help_text='所关联角色', max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='所关联角色'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='superior_menu',
            field=models.CharField(blank=True, default='', help_text='所配置菜单ID集合', max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='所配置菜单ID集合'),
        ),
    ]
